.PHONY:test
test:test2 test3 test4 test5 test6 test7 test8
	@echo "Congratulations: $@ passed"

.PHONY:test2
test2:
	@./allperms.py 2
	@echo "Congratulations: $@ passed"

.PHONY:test3
test3:
	@./allperms.py 3
	@echo "Congratulations: $@ passed"

.PHONY:test4
test4:
	@./allperms.py 4
	@echo "Congratulations: $@ passed"

.PHONY:test5
test5:
	@./allperms.py 5
	@echo "Congratulations: $@ passed"

.PHONY:test6
test6:
	@./allperms.py 6
	@echo "Congratulations: $@ passed"

.PHONY:test7
test7:
	@./allperms.py 7
	@echo "Congratulations: $@ passed"

.PHONY:test8
test8:
	@./allperms.py 8
	@echo "Congratulations: $@ passed"

.PHONY:clean
clean:
	@${RM} -r __pycache__
