.PHONY:test
test:
	./sort_dict.py
	./sort_dict_itemgetter.py
	./sort_pairs_stable.py
	./sort_proteins.py
	./sort_string_list.py
	./sort_string_list_by_len.py

.PHONY:clean
clean:
	${RM} -r __pycache__
